name: Deploy Application

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  migrations:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Migration Scripts
        run: |
          echo "Executing migrations..."
          ls migrations

  deploy-api:
    runs-on: ubuntu-latest
    needs: migrations

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build API
        run: |
          echo "Building API"

      - name: Deploy API
        run: |
          echo "Deploying API to Azure
